tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "on-primary-container": "#6b4900",
                        "background": "#131313",
                        "secondary-fixed-dim": "#c8c6c5",
                        "secondary-fixed": "#e4e2e1",
                        "on-error": "#690005",
                        "tertiary": "#cae0ff",
                        "outline": "#9e8e78",
                        "on-primary-fixed-variant": "#5f4100",
                        "on-primary-fixed": "#281900",
                        "on-background": "#e5e2e1",
                        "inverse-primary": "#7e5700",
                        "on-error-container": "#ffdad6",
                        "error-container": "#93000a",
                        "outline-variant": "#514532",
                        "secondary-container": "#474746",
                        "tertiary-fixed": "#d1e4ff",
                        "surface-container-high": "#2a2a2a",
                        "primary-fixed-dim": "#ffba35",
                        "primary": "#ffd89c",
                        "on-tertiary": "#103252",
                        "on-surface-variant": "#d6c4ac",
                        "surface-bright": "#393939",
                        "primary-fixed": "#ffdeac",
                        "error": "#ffb4ab",
                        "surface-variant": "#353534",
                        "surface-container-lowest": "#0e0e0e",
                        "surface-container-low": "#1c1b1b",
                        "surface": "#131313",
                        "on-surface": "#e5e2e1",
                        "tertiary-container": "#a7c5ec",
                        "on-primary": "#422c00",
                        "tertiary-fixed-dim": "#abc9f0",
                        "on-tertiary-container": "#345273",
                        "primary-container": "#ffb400",
                        "on-tertiary-fixed": "#001d36",
                        "surface-dim": "#131313",
                        "secondary": "#c8c6c5",
                        "inverse-surface": "#e5e2e1",
                        "on-secondary-fixed-variant": "#474746",
                        "surface-tint": "#ffba35",
                        "inverse-on-surface": "#313030",
                        "surface-container-highest": "#353534",
                        "on-secondary-container": "#b6b5b4",
                        "on-secondary-fixed": "#1b1c1c",
                        "surface-container": "#201f1f",
                        "on-tertiary-fixed-variant": "#2a4969",
                        "on-secondary": "#303030"
                    },
                    fontFamily: {
                        "headline": ["Manrope"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    },
                    borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
                },
            },
        }